### ISSUE TITLE
Does this require a more recent version of ArgoCD? 

### ISSUE THREAD

**Issue by dlactin** [argoproj-labs/argocd-ephemeral-access#58]
Hello! 

Trying this out in our sandbox environment with ArgoCD 2.11.2, the extension and CRDs install without any issues. 

I've created some RoleTemplate and AccessBinding resources with my desired permissions. I can see the `CURRENT PERMISSION` block but not the interface to request elevated permissions. 

Is there a requirement for 2.12 or a more recent version of Argo?

**Comment by leoluz** [comment]
Correct. The extension requires Argo CD 2.13. I updated the documentation with more installation details.
