### ISSUE TITLE
How is `roleName` populated? 

### ISSUE THREAD

**Issue by dlactin** [argoproj-labs/argocd-ephemeral-access#62]
I have set this up in a sandbox environment running ArgoCD 2.13.0. 

Escalation works well if I manually set a `roleName` in the body of a request, but I am having an issue with the initial request through the UI. 

It fails validation with this error `expected required property roleName to be present` and a `422` response code.  

![image](https://github.com/user-attachments/assets/7e742dfb-bf68-490c-b2bb-b53f1ab56b8b)

How is the `roleName` populated? I have created a few access bindings and roleTemplates using the default `devops` name as an example and still see this error.

**Comment by leoluz** [comment]
[Documentation updated](https://github.com/argoproj-labs/argocd-ephemeral-access/pull/63) with details about how to provide this configuration in the UI Extension
